# Generated by Django 2.2.12 on 2022-09-19 15:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_group', to='otree.Session')),
            ],
            options={
                'db_table': 'assessment_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'assessment_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('app_con_size', otree.db.models.StringField(choices=[('small', 'Liten'), ('medium', 'Mellomstor'), ('large', 'Stor')], max_length=10000, null=True)),
                ('app_con_owner_comment', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_habilitation_conflict', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_score_innovative', otree.db.models.StringField(choices=[('good', 'God'), ('average', 'Middels'), ('poor', 'Svak')], max_length=10000, null=True)),
                ('app_con_comment_innovative', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_score_prospects', otree.db.models.StringField(choices=[('good', 'God'), ('average', 'Middels'), ('poor', 'Svak')], max_length=10000, null=True)),
                ('app_con_comment_prospects', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_score_feasibility', otree.db.models.StringField(choices=[('good', 'God'), ('average', 'Middels'), ('poor', 'Svak')], max_length=10000, null=True)),
                ('app_con_comment_feasibility', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_sustainability', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_other_comments', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_women', otree.db.models.StringField(choices=[('no_choice', 'Ikke valgt'), ('yes', 'Ja'), ('no', 'Nei')], max_length=10000, null=True)),
                ('app_con_w_1', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Medeier eller oppstart')),
                ('app_con_w_2', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Kompetanseøkning')),
                ('app_con_w_3', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='> 30 \\% av styre eller ledelse')),
                ('app_con_w_4', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Øke kvinners deltakelse')),
                ('app_con_risk', otree.db.models.IntegerField(choices=[(1, '1 - Lav'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6 - Høy')], null=True)),
                ('app_con_businessrisk', otree.db.models.StringField(choices=[('A', 'A - Lav'), ('B', 'B - Middels'), ('C', 'C - Høy'), ('D', 'D - Ekstra høy')], max_length=10000, null=True)),
                ('app_con_innovation', otree.db.models.StringField(choices=[('business', 'Innovasjon på bedriftsnivå'), ('regional', 'Innovasjon på regionalt nivå'), ('national', 'Innovasjon på nasjonalt nivå'), ('international', 'Innovasjon på internasjonalt nivå'), ('not_applies', 'Ikke relevant')], max_length=10000, null=True)),
                ('app_con_innovation_type', otree.db.models.StringField(choices=[('product', 'Produkt-/tjenesteinnovasjon'), ('process', 'Prosessinnovasjon'), ('organisation', 'Organisatorisk innovasjon'), ('market', 'Markedsmessig innovasjon')], max_length=10000, null=True)),
                ('app_con_sector', otree.db.models.StringField(choices=[('energy', 'Energi og miljø'), ('health', 'Helse'), ('agricultural', 'Landbruk'), ('marine', 'Marin'), ('maritime', 'Maritim'), ('oil', 'Olje og gass'), ('tourism', 'Reiseliv'), ('not_listed', 'Ikke satsingsområde')], max_length=10000, null=True)),
                ('app_con_environment', otree.db.models.StringField(choices=[('no_choice', 'Ikke valgt'), ('yes', 'Ja'), ('no', 'Nei')], max_length=10000, null=True)),
                ('app_con_e_1', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Produksjon av fornybar energi')),
                ('app_con_e_2', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Reduksjon i utslipp av klimagasser')),
                ('app_con_e_3', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Vannbehandling')),
                ('app_con_e_4', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Bedre utnyttelse av biologiske ressurser')),
                ('app_con_e_5', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Energieffektivisering')),
                ('app_con_e_6', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Andre tiltak/løsninger')),
                ('app_con_e_7', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Redusert luftforurensing ellers')),
                ('app_con_e_8', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Energiutnyttelse av avløpsrør, avløpsslam, spillvarme, avgasser (Waste to energy)')),
                ('app_con_e_9', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Bedre utnyttelse av uorganiske ressurser og mineraler')),
                ('app_con_e_10', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Materialgjenvinning')),
                ('app_con_e_11', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Redusert bruk av kjemikalier, antibiotika, andre skadelige stoffer')),
                ('app_con_society', otree.db.models.StringField(choices=[('no_choice', 'Ikke valgt'), ('yes', 'Ja'), ('no', 'Nei')], max_length=10000, null=True)),
                ('app_con_s_1', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Helse og velferd')),
                ('app_con_s_2', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Et tryggere samfunn / økt beredskap og sikkerhet')),
                ('app_con_s_3', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Økt dyrevelferd')),
                ('app_con_s_4', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Økt tilgang på utdanning, forskning eller andre kunnskapshevende tiltak')),
                ('app_con_s_5', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Løsninger på andre utfordringer i samfunnet, nasjonalt eller internasjonalt')),
                ('app_con_coststudy_offered', otree.db.models.IntegerField(blank=True, null=True)),
                ('app_con_costmws_offered', otree.db.models.IntegerField(blank=True, null=True)),
                ('app_con_costnetwork_offered', otree.db.models.IntegerField(blank=True, null=True)),
                ('app_con_costcomp_offered', otree.db.models.IntegerField(blank=True, null=True)),
                ('app_con_INfund_finoffered', otree.db.models.IntegerField(blank=True, null=True)),
                ('app_con_AFfund_finoffered', otree.db.models.IntegerField(blank=True, null=True)),
                ('app_con_partial_funding', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_no_funding', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('app_con_internal_comment', otree.db.models.LongStringField(blank=True, null=True, verbose_name='')),
                ('case_label', otree.db.models.LongStringField(null=True)),
                ('treatment_bool', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Subsession')),
            ],
            options={
                'db_table': 'assessment_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Subsession'),
        ),
    ]
